name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  releases:
    runs-on: ubuntu-latest
    steps: 
    - name: Check ENV
      run: |
        echo "GITHUB_JOB $GITHUB_JOB"
        echo "GITHUB_RUN_NUMBER $GITHUB_RUN_NUMBER"
        
        
    - name: "Create GitHub Release"
      id: create_release
      uses: actions/github-script@v5
      env:
        JOB_NUMBER: $GITHUB_RUN_NUMBER
      with:
        script: |
          console.log(`1 Hello JOB_NUMBER ${JOB_NUMBER} GITHUB_RUN_NUMBER ${GITHUB_RUN_NUMBER}`)
          console.log('2 Hello JOB_NUMBER ${JOB_NUMBER} GITHUB_RUN_NUMBER ${GITHUB_RUN_NUMBER}')
          console.log("3 Hello JOB_NUMBER ${JOB_NUMBER} GITHUB_RUN_NUMBER ${GITHUB_RUN_NUMBER}")
          
#         github.rest.repos.createRelease({
#           owner: context.repo.owner,
#           repo: context.repo.repo,
#           tag_name: ${JOB_NUMBER}v`
#         });    


  build_macosx:
    needs: releases
    runs-on: macos-latest    
    steps: 
    - name: "Get latest GitHub Release"
      id: get_release
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
         
    - uses: actions/checkout@v2
    
    - name: Build for Macos
      run: |
        cd HelloVapor
        swift build
      
#     - name: Upload release assets for Macos
#       uses: actions/upload-release-asset@v1.0.1
#       with:
#         upload_url: ${{ steps.get_release.outputs.upload_url }}
#         asset_path: target/release/dmenv
#         asset_name: dmenv-linux

  
  build_linux:
    needs: releases
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-5.5-bionic
    steps:
    - name: "Get latest GitHub Release"
      id: get_release
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

    - uses: actions/checkout@v2

    - name: Build for Linux
      run: |
        cd HelloVapor
        swift build
